/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agency {
  'id' : string,
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'description' : [] | [string],
  'createdTimestamp' : Time,
  'isValid' : boolean,
}
export interface Location {
  'latitude' : number,
  'country' : string,
  'city' : string,
  'longitude' : number,
}
export interface LogonActivity { 'logon' : string, 'timestamp' : Time }
export interface Profile {
  'age' : [] | [bigint],
  'bio' : [] | [string],
  'diamonds' : bigint,
  'createdAt' : Time,
  'coins' : bigint,
  'upgrades' : Array<Upgrade>,
  'email' : [] | [string],
  'hasAgreedToTerms' : boolean,
  'socialMediaLinks' : Array<SocialMediaLink>,
  'logonActivity' : Array<LogonActivity>,
  'avatarUrl' : [] | [string],
  'birthday' : [] | [Time],
  'interestedIn' : [] | [string],
  'gender' : string,
  'lastActive' : bigint,
  'location' : [] | [Location],
  'photos' : Array<string>,
  'firstName' : string,
}
export interface SocialMediaLink { 'url' : string, 'platform' : string }
export type Time = bigint;
export interface Upgrade {
  'id' : string,
  'user' : Principal,
  'description' : string,
  'timestamp' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptMembershipRequest' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAgency' : ActorMethod<[string, [] | [string]], Agency>,
  'creditWallet' : ActorMethod<[bigint, bigint], undefined>,
  'debitWallet' : ActorMethod<[bigint, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinAgency' : ActorMethod<[string], undefined>,
  'registerProfile' : ActorMethod<[string, string], Profile>,
  'requestMembership' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];