/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Agency = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'createdTimestamp' : Time,
  'isValid' : IDL.Bool,
});
export const Upgrade = IDL.Record({
  'id' : IDL.Text,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const SocialMediaLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const LogonActivity = IDL.Record({
  'logon' : IDL.Text,
  'timestamp' : Time,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const Profile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'bio' : IDL.Opt(IDL.Text),
  'diamonds' : IDL.Nat,
  'createdAt' : Time,
  'coins' : IDL.Nat,
  'upgrades' : IDL.Vec(Upgrade),
  'email' : IDL.Opt(IDL.Text),
  'hasAgreedToTerms' : IDL.Bool,
  'socialMediaLinks' : IDL.Vec(SocialMediaLink),
  'logonActivity' : IDL.Vec(LogonActivity),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'birthday' : IDL.Opt(Time),
  'interestedIn' : IDL.Opt(IDL.Text),
  'gender' : IDL.Text,
  'lastActive' : IDL.Int,
  'location' : IDL.Opt(Location),
  'photos' : IDL.Vec(IDL.Text),
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptMembershipRequest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAgency' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Agency], []),
  'creditWallet' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'debitWallet' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinAgency' : IDL.Func([IDL.Text], [], []),
  'registerProfile' : IDL.Func([IDL.Text, IDL.Text], [Profile], []),
  'requestMembership' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Agency = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'createdTimestamp' : Time,
    'isValid' : IDL.Bool,
  });
  const Upgrade = IDL.Record({
    'id' : IDL.Text,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const SocialMediaLink = IDL.Record({
    'url' : IDL.Text,
    'platform' : IDL.Text,
  });
  const LogonActivity = IDL.Record({ 'logon' : IDL.Text, 'timestamp' : Time });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const Profile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'bio' : IDL.Opt(IDL.Text),
    'diamonds' : IDL.Nat,
    'createdAt' : Time,
    'coins' : IDL.Nat,
    'upgrades' : IDL.Vec(Upgrade),
    'email' : IDL.Opt(IDL.Text),
    'hasAgreedToTerms' : IDL.Bool,
    'socialMediaLinks' : IDL.Vec(SocialMediaLink),
    'logonActivity' : IDL.Vec(LogonActivity),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'birthday' : IDL.Opt(Time),
    'interestedIn' : IDL.Opt(IDL.Text),
    'gender' : IDL.Text,
    'lastActive' : IDL.Int,
    'location' : IDL.Opt(Location),
    'photos' : IDL.Vec(IDL.Text),
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptMembershipRequest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAgency' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Agency], []),
    'creditWallet' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'debitWallet' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinAgency' : IDL.Func([IDL.Text], [], []),
    'registerProfile' : IDL.Func([IDL.Text, IDL.Text], [Profile], []),
    'requestMembership' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };