/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    country: string;
    city: string;
    longitude: number;
}
export interface LogonActivity {
    logon: string;
    timestamp: Time;
}
export type Time = bigint;
export interface Upgrade {
    id: string;
    user: Principal;
    description: string;
    timestamp: Time;
}
export interface SocialMediaLink {
    url: string;
    platform: string;
}
export interface Profile {
    age?: bigint;
    bio?: string;
    diamonds: bigint;
    createdAt: Time;
    coins: bigint;
    upgrades: Array<Upgrade>;
    email?: string;
    hasAgreedToTerms: boolean;
    socialMediaLinks: Array<SocialMediaLink>;
    logonActivity: Array<LogonActivity>;
    avatarUrl?: string;
    birthday?: Time;
    interestedIn?: string;
    gender: string;
    lastActive: bigint;
    location?: Location;
    photos: Array<string>;
    firstName: string;
}
export interface Agency {
    id: string;
    creator: Principal;
    members: Array<Principal>;
    name: string;
    description?: string;
    createdTimestamp: Time;
    isValid: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptMembershipRequest(memberName: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAgency(name: string, description: string | null): Promise<Agency>;
    creditWallet(amountCoins: bigint, amountDiamonds: bigint): Promise<void>;
    debitWallet(amountCoins: bigint, amountDiamonds: bigint): Promise<void>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinAgency(agencyId: string): Promise<void>;
    registerProfile(firstName: string, gender: string): Promise<Profile>;
    requestMembership(memberName: string, description: string): Promise<void>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
}
import type { Agency as _Agency, Location as _Location, LogonActivity as _LogonActivity, Profile as _Profile, SocialMediaLink as _SocialMediaLink, Time as _Time, Upgrade as _Upgrade, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptMembershipRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptMembershipRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptMembershipRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAgency(arg0: string, arg1: string | null): Promise<Agency> {
        if (this.processError) {
            try {
                const result = await this.actor.createAgency(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Agency_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAgency(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Agency_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async creditWallet(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.creditWallet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.creditWallet(arg0, arg1);
            return result;
        }
    }
    async debitWallet(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.debitWallet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debitWallet(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinAgency(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinAgency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinAgency(arg0);
            return result;
        }
    }
    async registerProfile(arg0: string, arg1: string): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(arg0, arg1);
                return from_candid_Profile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(arg0, arg1);
            return from_candid_Profile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestMembership(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestMembership(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestMembership(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Agency_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agency): Agency {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: Principal;
    members: Array<Principal>;
    name: string;
    description: [] | [string];
    createdTimestamp: _Time;
    isValid: boolean;
}): {
    id: string;
    creator: Principal;
    members: Array<Principal>;
    name: string;
    description?: string;
    createdTimestamp: Time;
    isValid: boolean;
} {
    return {
        id: value.id,
        creator: value.creator,
        members: value.members,
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.description)),
        createdTimestamp: value.createdTimestamp,
        isValid: value.isValid
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: [] | [bigint];
    bio: [] | [string];
    diamonds: bigint;
    createdAt: _Time;
    coins: bigint;
    upgrades: Array<_Upgrade>;
    email: [] | [string];
    hasAgreedToTerms: boolean;
    socialMediaLinks: Array<_SocialMediaLink>;
    logonActivity: Array<_LogonActivity>;
    avatarUrl: [] | [string];
    birthday: [] | [_Time];
    interestedIn: [] | [string];
    gender: string;
    lastActive: bigint;
    location: [] | [_Location];
    photos: Array<string>;
    firstName: string;
}): {
    age?: bigint;
    bio?: string;
    diamonds: bigint;
    createdAt: Time;
    coins: bigint;
    upgrades: Array<Upgrade>;
    email?: string;
    hasAgreedToTerms: boolean;
    socialMediaLinks: Array<SocialMediaLink>;
    logonActivity: Array<LogonActivity>;
    avatarUrl?: string;
    birthday?: Time;
    interestedIn?: string;
    gender: string;
    lastActive: bigint;
    location?: Location;
    photos: Array<string>;
    firstName: string;
} {
    return {
        age: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.age)),
        bio: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.bio)),
        diamonds: value.diamonds,
        createdAt: value.createdAt,
        coins: value.coins,
        upgrades: value.upgrades,
        email: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.email)),
        hasAgreedToTerms: value.hasAgreedToTerms,
        socialMediaLinks: value.socialMediaLinks,
        logonActivity: value.logonActivity,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.avatarUrl)),
        birthday: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.birthday)),
        interestedIn: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.interestedIn)),
        gender: value.gender,
        lastActive: value.lastActive,
        location: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.location)),
        photos: value.photos,
        firstName: value.firstName
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_Profile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    bio?: string;
    diamonds: bigint;
    createdAt: Time;
    coins: bigint;
    upgrades: Array<Upgrade>;
    email?: string;
    hasAgreedToTerms: boolean;
    socialMediaLinks: Array<SocialMediaLink>;
    logonActivity: Array<LogonActivity>;
    avatarUrl?: string;
    birthday?: Time;
    interestedIn?: string;
    gender: string;
    lastActive: bigint;
    location?: Location;
    photos: Array<string>;
    firstName: string;
}): {
    age: [] | [bigint];
    bio: [] | [string];
    diamonds: bigint;
    createdAt: _Time;
    coins: bigint;
    upgrades: Array<_Upgrade>;
    email: [] | [string];
    hasAgreedToTerms: boolean;
    socialMediaLinks: Array<_SocialMediaLink>;
    logonActivity: Array<_LogonActivity>;
    avatarUrl: [] | [string];
    birthday: [] | [_Time];
    interestedIn: [] | [string];
    gender: string;
    lastActive: bigint;
    location: [] | [_Location];
    photos: Array<string>;
    firstName: string;
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        diamonds: value.diamonds,
        createdAt: value.createdAt,
        coins: value.coins,
        upgrades: value.upgrades,
        email: value.email ? candid_some(value.email) : candid_none(),
        hasAgreedToTerms: value.hasAgreedToTerms,
        socialMediaLinks: value.socialMediaLinks,
        logonActivity: value.logonActivity,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        birthday: value.birthday ? candid_some(value.birthday) : candid_none(),
        interestedIn: value.interestedIn ? candid_some(value.interestedIn) : candid_none(),
        gender: value.gender,
        lastActive: value.lastActive,
        location: value.location ? candid_some(value.location) : candid_none(),
        photos: value.photos,
        firstName: value.firstName
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
